apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: virtink-system/virt-controller-cert
webhooks:
  - name: mutate.virtualmachine.v1alpha1.virt.virtink.smartx.com
    clientConfig:
      service:
        name: virt-controller
        namespace: virtink-system
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: virtink-system/virt-controller-cert
webhooks:
  - name: validate.virtualmachine.v1alpha1.virt.virtink.smartx.com
    clientConfig:
      service:
        name: virt-controller
        namespace: virtink-system
  - name: validate.virtualmachinemigration.v1alpha1.virt.virtink.smartx.com
    clientConfig:
      service:
        name: virt-controller
        namespace: virtink-system
