name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: smartxrocks
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          file: build/virt-controller/Dockerfile
          tags: smartxworks/virt-controller:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/virt-daemon/Dockerfile
          tags: smartxworks/virt-daemon:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/virt-prerunner/Dockerfile
          tags: smartxworks/virt-prerunner:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/virtink-container-disk-base/Dockerfile
          tags: smartxworks/virtink-container-disk-base
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/virtink-kernel-base/Dockerfile
          tags: smartxworks/virtink-kernel-base
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/virtink-container-rootfs-base/Dockerfile
          tags: smartxworks/virtink-container-rootfs-base
          push: true

      - run: |
          curl -sLo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x /tmp/skaffold
          /tmp/skaffold render --default-repo=smartxworks --offline=true > virtink.yaml

      - uses: softprops/action-gh-release@v1
        with:
          files: virtink.yaml
