name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          file: build/kubrid-controller/Dockerfile
          tags: smartxworks/kubrid-controller:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/kubrid-daemon/Dockerfile
          tags: smartxworks/kubrid-daemon:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/kubrid-prerunner/Dockerfile
          tags: smartxworks/kubrid-prerunner:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/container-disk-base/Dockerfile
          tags: smartxworks/kubrid-container-disk-base
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/kernel-base/Dockerfile
          tags: smartxworks/kubrid-kernel-base
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/container-rootfs-base/Dockerfile
          tags: smartxworks/kubrid-container-rootfs-base
          push: true

      - run: |
          curl -sLo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x /tmp/skaffold
          /tmp/skaffold render --default-repo=smartxworks --offline=true > kubrid.yaml

      - uses: softprops/action-gh-release@v1
        with:
          files: kubrid.yaml
